language: go

install:
    - go get github.com/gohugoio/hugo

before_script:
    - rm -rf public

script:
    - hugo

deploy:
  provider: s3
  access_key_id: AKIAIAXYAK4BPCG7D7UA
  secret_access_key:
    secure: Xb3+YS1phkcvY/gRLOWLtSNefR+6gzRmyOQ6+wbPfBkvSd0BN9OxskHDaXhZk8TX/BFFejBHpFV+bnE48sRVjDV51tuQ+QLSuA+bWK+zbQ6kpxOTQKNe5tnF2rcpIejcl8lLoGhUM2zU5p7F8E4iOz2ckySMx1mAOCe/l/bajM31Jdt4QfMZzYeowFzqz7EOfIsK3NDWW1MdT2lOpAr7ZeYBNl3jOj2RG5YFM/69zlW6o+ZPjd02yAjESe7XUg/KeSRWiyehPFI6pHNGB08uRfpL9Z3RaXUmKkiLd/hlEZ2VxfPj2LLwjF+8cNhSXDRLh/ZQccn8wYLLUr7aci5xuYaJLPpUUWz8PQV7gcQEv3Pd1gB27JWZAittuDSjJxQ69ilGNWxDqlSldkpqRlclQpdjP5CSuO6r4ZmvxQTEDecho69PIF/8WRQiJTUYydCuP6Yy0n4ERErtZBHiLh1Ov39BZTpq8l9riTu9DeyCSUXyu4ixzlgHNab8CgwIsSWWrgwb/rzrInYy2OJsUUBybD7rDsVvPy0a2IZbwUO/aoVEDFbq3Ni9z+G/KtktLwq3tlTQNvSKCK24ysC21XJtkIO7jUtiNDClzlW9EBUfiv1Z30JHi6C+SaP0QwMHCgH8aUATBhkDw9lumxcszomJ7XARAXlrtURXuouQbGHbxNw=
  bucket: www.fabiooliveira.me
  skip_cleanup: true
  region: eu-central-1
  local_dir: public
