language: go
install:
- go get github.com/gohugoio/hugo
before_script:
- rm -rf public
script:
- hugo
deploy:
  provider: s3
  bucket: www.fabiooliveira.me
  skip_cleanup: true
  region: eu-central-1
  local_dir: public
  acl: public_read
  access_key_id: AKIAIAXYAK4BPCG7D7UA
  secret_access_key:
    secure: VT/pQoLZxGPOnvSVwR5raWuUD5+EET+UVwdnYlldyItHcHxuj5iJ7ioO31yBP1SaIPyceznITLNHvRgW6986FTAsyc2Oj2lzvkPO3evifDEPwfngTLwHAJrPXUYlNO24GLVJgoxb60caZJMrzh9Wqf2X2X2ZHlpU5JdDpdmg2tU1k4E4oX/6fGjeTcbfzefCFqSaW/FTCx9QNOdRhkcscqY/6b7q8+JGd6l+cfUUA+M8u8Xf/nF5mOErtE0dmUsCJ5/X73DQ+vjZsSVStSIBGERIVvWYizWEEs1EGgiSh6/yrDy9ZnQg2zJkeHAXhWwyFb2NuY1YJXA3VL9fuvzlEjScBeqDGUgReUJ7mz+1IlH+vuRMbMGbFZ8ExVdA80f5lwnwLK09xC/xUYIBuGKxiVMyAJeG3vsN6Ao+pSK7RCi3pRRgRdpW9UGfIY9BaIx/zHXQvFecwvnDCv9Rl+ICaL1LJExytWwBPspmXnT5LAhPYVXYYdZJJFrWF/QK9/CmzquqiqUnXPHcajivNfbJl4HZTkNpqfp66yo7nagwF6tGlB8KfneRoac43ts3fF89eJDX64k8ByoKEvzcY7pw+l1/R13nujuHqivGkZKcXhW5momJVhg4cWQZS8ft2hxUXMteNBd6XvZIpHqs/wDEa3TbU3acJo1x3uPT2kbVsQY=
