language: go
install:
- go get github.com/gohugoio/hugo
before_script:
- rm -rf public
script:
- hugo
deploy:
  provider: s3
  access_key_id: AKIAIAXYAK4BPCG7D7UA
  secret_access_key:
    secure: XaDp+CmWz8KzA47W5n5FPcongpvMGz2HXBXdg11ohNA06b4v2qNrfqAnK65GN4moYBUraLy7ovHWA9eKlQLRR4ElKTnA0rF9Q/xGePuSMWq9zwy4JamfIq8aDv120B3jz5F0jjA4/cDcnXeJQrjjfBAgQH/NXFw009SDedkq8qlxN9MkYFqgUDLIlv3BIe5Oufcdf805ETcm7vwT/5hLDm/q1asdPTihK7GsiY9RdmbsC+w6dDW+GRgIiC+heNdfA4zTwBB37x9ERZ0FqWgPig6ejhg49tCMcDD3zdkUWfo2aSvinbL8FH6CXTRYrAzRhVlj1xDH806ZbmKGrpL9ovO/VwLdAeVX7Ket7mtQ8glNOawak5Kik5MYan+7MnaDBOlroCXY6IFVaQ65QJ1zIGp7diCvd8IvSICsn1BLA+juzP6OBPpI8zI4LqYyH1SN/C1VrUw65/gWevLUUebP2GJHMkDz0RR15qS8OPkc2N+vAUSd2Nc+v0nq5UG/k4juh1MXuZ/3afnHuxTfX6QrIYITCGXdSpCTRGp0QMrWUu0f+20JEuNwZ9VLMEEsP9oxyjtfdeX4ZzkEhIyo3i+dTpHduTaZvKgiShb8M6DMFJTB1spxE0AmrQwITjaYLl/B7WhpYqQp/yAWl99qHkuybPXoXVenv9y21/Q8vETQSfs=
  bucket: www.fabiooliveira.me
  skip_cleanup: true
  local-dir: public
  acl: public_read
