baseurl = "http://www.fabiooliveira.me"
title = "fabiooliveira"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "fabiooliveira-me"

googleAnalytics = "UA-132353875-1"

uglyURLs = true

[params]
    author = "Fabio Oliveira"
    description = "Fabio Oliveira's personal website"
    keywords = "blog,developer,personal,software,cloud,agile,devops"
    info = "Solution Architect, Cloud, Agile Coach, DevOps, Polyglot Software Engineer and everything else..."
    avatarurl = "images/fabio.jpeg"
    footercontent = "Not always right, but always learning"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/fbdo/site/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/fbdo/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/fbdo/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/fabiobragaoliveira/"
# [[params.social]]
#    name = "Medium"
#    icon = "fab fa-medium"
#    weight = 5
#    url = "https://medium.com/@johndoe"


[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Fabio Oliveira"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Fabio Oliveira"
        info = "Solution Architect, Cloud, Agile Coach, DevOps, Polyglot Software Engineer and everything else..."
        description = "Fabio Oliveira's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "Résumé"
        weight = 1
        url = "https://fbdo.github.io/resume/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts.html"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "https://github.com/fbdo?tab=repositories"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "https://twitter.com/messages/compose?recipient_id=31106182"
